config/routes.rb
Dcid::Application.routes.draw do
  resources :users
  resources :password_resets
  resources :sessions,  only: [:new, :create, :destroy]
  resources :proposals do
    member do
      post :vote_for, :vote_against
    end
  end

  root 'static_pages#home'

  get   '/tags/:tag', to: 'proposals#tagged',   :as => 'tag'
  match '/tags',      to: 'proposals#tags',     via: 'get'
  match '/change_proposal_order', to: 'proposals#change_order', via: 'get'

  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/how',     to: 'static_pages#how',     via: 'get'
  match '/terms',   to: 'static_pages#terms',   via: 'get'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404', via: 'get'
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'Sobre nós') %>

<div class="row">
  <div class="col-md-12 text-center">
    <p><%= image_tag("logo-dcid.png", alt: "DCID logo", width: "350") %></p>
    <br/>
    <p class="lead"><strong>DCID é uma plataforma colaborativa online que permite a qualquer organização recolher e debater sugestões da sua comunidade.</strong></p>
  </div>
</div>

<br/>

<div class="row">
  <div class="col-md-12">
    <div class="row">
      <div class="col-md-4">
        <h4><%= image_tag("logo-dcid-head.png", alt: "*", width: "25", height: "25") %>&nbsp;Colaboração</h4>
        <p>Qualquer participante pode criar, apresentar e discutir sugestões em conjunto, num único local.</p>
        <br/>
      </div>
      <div class="col-md-4">
        <h4><%= image_tag("logo-dcid-head.png", alt: "*", width: "25", height: "25") %>&nbsp;Facilidade</h4>
        <p>Basta um registo, não precisa instalar nada. Uma interface minimalista e intuitiva, que se adapta ao dispositivo de cada utilizador.</p>
        <br/>
      </div>
      <div class="col-md-4">
        <h4><%= image_tag("logo-dcid-head.png", alt: "*", width: "25", height: "25") %>&nbsp;Transparência</h4>
        <p>Os participantes têm acesso a todas as propostas em discussão e ao respectivo número de votos.</p>
        <br/>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4">
        <h4><%= image_tag("logo-dcid-head.png", alt: "*", width: "25", height: "25") %>&nbsp;Eficiência</h4>
        <p>Recolha sugestões de dezenas ou milhares de participantes com a mesma facilidade e rapidez.</p>
        <br/>
      </div>
      <div class="col-md-4">
        <h4><%= image_tag("logo-dcid-head.png", alt: "*", width: "25", height: "25") %>&nbsp;Flexibilidade</h4>
        <p>O aspecto da plataforma é personalizável a cada organização. Também podemos desenvolver funcionalidades à medida das suas necessidades.</p>
        <br/>
      </div>
      <div class="col-md-4">
        <h4><%= image_tag("logo-dcid-head.png", alt: "*", width: "25", height: "25") %>&nbsp;Privacidade</h4>
        <p>Torne a sua plataforma pública para a toda a gente poder participar ou torne-a privada para proteger a sua inovação interna.</p>
        <br/>
      </div>
    </div>
  </div>
</div>

<br>

<div class="row">
  <div class="col-md-12">

    <h1>Quem somos?</h1>

    <p align="justify">Esta plataforma foi criada pelo Code4PT. Inspirado no movimento <a href="http://codeforamerica.org/">Code For America</a>, o Code4PT é um movimento de programadores portugueses que doam o seu tempo para criar soluções tecnológicas que melhorem a vida dos portugueses.</p>
    <p align="justify">Nesse sentido, o DCID pretende ser uma ferramenta que potencie a participação cívica e construtiva de todos os portugueses. O conteúdo e opiniões publicadas nesta plataforma são da exclusiva responsabilidade dos seus autores e não podem ser associadas ao Code4PT ou aos seus elementos.</p>

    <p class="text-center"><em>Sê a mudança que queres ver no mundo.</em> -- Mahatma Gandhi</p>
    <p class="text-center">Tudo começa com uma pessoa.</p>
    <p class="text-center"><strong>Você.</strong></p>
    <p class="text-center">Agora DCID.</p>

    <p class="pull-right">por <a href="http://www.diogonunes.com/sobre-mim">Diogo Nunes</a><p>

  </div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, '') %>

<% if signed_in? %>


<div class="row">
  <div class="col-md-12 text-center">
    <%= image_tag("logo-dcid.png", alt: "DCID logo", class: "logo") %>
  </div>
</div>

<br>

<div class="row">
  <div class="col-md-4 col-md-offset-2 text-center">
    <i class="fa fa-bullhorn fa-4x"></i>
    <br><br>
    <%= link_to 'Propor', new_proposal_path, class: "btn btn-default btn-success btn-lg" %>
  </div>
  <br class="visible-xs"><!-- separates divs -->
  <div class="col-md-4 text-center">
    <i class="fa fa-thumbs-o-up fa-4x"></i>
    <br><br>
    <%= link_to 'Decidir', proposals_path, class: "btn btn-default btn-success btn-lg" %>
  </div>
</div>


<% else %>


<div class="row">
  <div class="col-md-12 text-center">
    <h1><%= link_to image_tag("logo-dcid.png", alt: "DCID logo", class: "logo"), signup_path %></h1>
  </div>
</div>

<br>

<div class="row">
  <div class="col-md-4 text-center">
    <i class="fa fa-bullhorn fa-4x"></i>
    <h2><strong>Propor</strong></h2>
    <p class="">Faça a sua voz ser ouvida</p>
  </div>
  <div class="col-md-4 text-center">
    <i class="fa fa-comments fa-4x"></i>
    <h2><strong>Debater</strong></h2>
    <p class="">Melhore a sua proposta</p>
  </div>
  <div class="col-md-4 text-center">
    <i class="fa fa-thumbs-o-up fa-4x"></i>
    <h2><strong>Decidir</strong></h2>
    <p class="">Junte apoiantes e faça acontecer</p>
  </div>
</div>

<br><br>

<div class="row">
  <div class="col-md-12 text-center">
    <%= link_to 'Participe!', signup_path, class: "btn btn-default btn-success btn-lg" %>
  </div>
</div>


<% end %>

app/views/static_pages/how.html.erb
<% provide(:title, 'Como funciona') %>

<div class="row">
  <div class="col-md-12">

    <h1>Como funciona?</h1>

    <br>

    <div class="row">
      <div class="col-md-3 text-center">
        <i class="fa fa-sign-in fa-4x"></i>
        <h2><strong>Registar</strong></h2>
        <p>Para participar precisa apenas de criar um perfil. Só lhe pedimos alguns dados essenciais e é você que decide se eles são públicos ou não.</p>
      </div>
      <div class="col-md-3 text-center">
        <i class="fa fa-comments fa-4x"></i>
        <h2><strong>Propor</strong></h2>
        <p>Apresente problemas e sugira soluções. Seja construtivo, use o bom-senso e pense a longo-prazo. Oiça sugestões e melhore a sua proposta.</p>
      </div>
      <div class="col-md-3 text-center">
        <i class="fa fa-check-square-o fa-4x"></i>
        <h2><strong>Votar</strong></h2>
        <p>Exerça o seu poder de decisão e decida que propostas devem ser implementadas. O seu voto é único e secreto, como sempre.</p>
      </div>
      <div class="col-md-3 text-center">
        <i class="fa fa-users fa-4x"></i>
        <h2><strong>Partilhar</strong></h2>
        <p>Tire partido da sua rede de contactos e obtenha mais votos. Quantos mais formos mais expressivas e democráticas serão as votações.</p>
      </div>
    </div>

    <br>

    <div class="text-center">
      <%= link_to '<button class="btn btn-default btn-success btn-lg">Comece a decidir, <strong>agora!</strong></button>'.html_safe, signup_path %>
    </div>

  </div>
</div>

app/views/static_pages/terms.html.erb
<% provide(:title, 'Termos de utilização') %>

<div class="row">
  <div class="col-md-12">

    <h1>Termos de utilização</h1>

    <h3>Resumo</h3>
    <p><ul>
      <li>O DCID não é um produto acabado. Sendo um protótipo, é possível que falhe, na pior altura, da pior maneira. Obrigado pela sua compreensão.</li>
      <li>A única informação pessoal que guardamos são os dados que o utilizador nos fornece durante o seu registo. Prometemos protegê-los.</li>
      <li>O conteúdo e opiniões publicadas nesta plataforma são da exclusiva responsabilidade dos seus respectivos autores e não podem ser associadas ao DCID, ao Code4PT ou a qualquer dos seus elementos. Somos apenas uma ferramenta.</li>
    </ul></p>

    <p>Todas as suas informações pessoais recolhidas serão usadas para permitir uma utilização eficaz do DCID. A informação pessoal recolhida inclui o seu nome, e-mail, número de bilhete de identidade ou cartão de cidadão. Estes dados são fornecidos voluntariamente pelo utilizador aquando do seu registo. Utilizamos cookies para armazenar as suas preferências pessoais quando visita a nossa plataforma. O utilizador detém o poder de desligar os seus cookies, nas opções do seu browser.</p>
    <p>O DCID pode possuir ligações para outros sites, os quais, a nosso ver, podem conter informações úteis para os nossos utilizadores. A nossa política de privacidade não é aplicada a sites de terceiros, pelo que, caso visite outro site a partir do nosso deverá ler a política de privacidade do mesmo. Não nos responsabilizamos pela política de privacidade ou conteúdo presente nesses mesmos sites.</p>
    <p>A plataforma DCID guarda conteúdo criado pelos seus utilizadores. Esse conteúdo é da inteira responsabilidade do(s) seu(s) autor(es). O DCID é apenas uma ferramenta. O movimento Code4PT e os seus elementos, não podem de forma alguma ser associados ao conteúdo e opiniões deixadas na plataforma.</p>
    <p>Ao utilizar a plataforma DCID está a aceitar estes termos.</p>

  </div>
</div>