config/routes.rb
Dcid::Application.routes.draw do
  resources :users
  resources :password_resets
  resources :sessions,  only: [:new, :create, :destroy]
  resources :proposals do
    member do
      post :vote_for, :vote_against
    end
  end

  root 'static_pages#home'

  get   '/tags/:tag', to: 'proposals#tagged',   :as => 'tag'
  match '/tags',      to: 'proposals#tags',     via: 'get'
  match '/change_proposal_order', to: 'proposals#change_order', via: 'get'

  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/how',     to: 'static_pages#how',     via: 'get'
  match '/terms',   to: 'static_pages#terms',   via: 'get'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404', via: 'get'
  end

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      Há <%= pluralize(object.errors.count, "problema") %> com o seu preenchimento.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_link_to_user.html.erb
<% if user.is_name_public %>
  <%= link_to user.short_name, user %>
<% else %>
  <%= user.short_name %>
<% end %>

<% if not user.political_party.empty? %>
  <% if    user.political_party == 'PSD' or user.political_party == 'PPD/PSD' %>
    <span class="badge bkg-orange">
  <% elsif user.political_party == 'CDS' or user.political_party == 'CDS-PP' %>
    <span class="badge bkg-blue">
  <% elsif user.political_party == 'PS' %>
    <span class="badge bkg-pink">
  <% elsif user.political_party == 'PCP' %>
    <span class="badge bkg-red">
  <% elsif user.political_party == 'BE' %>
    <span class="badge bkg-inverse">
  <% elsif user.political_party == 'PEV'   or
           user.political_party == 'LIVRE' or
           user.political_party == 'PAN'   or
           user.political_party == 'MPT' %>
    <span class="badge bkg-green">
  <% else %>
    <span class="badge">
  <% end %>
  <%= user.political_party %></span>
<% end %>

app/views/shared/_list_tag_labels.html.erb
<% if tags.any? %>
  <% tags.each do |name| %>
    <span class="text-center"><%= render 'shared/tag_label', :tag_name => name %></span><br>
  <% end %>
<% end %>

app/views/shared/_span_tag_labels.html.erb
<% if tags.any? %>
  <% tags.each do |name| %>
    <%= render 'shared/tag_label', :tag_name => name %>&nbsp;
  <% end %>
<% end %>

app/views/shared/_tag_label.html.erb
<a class="label label-default" title="Ver propostas do mesmo tema" href="<%= tag_path(tag_name) %>"><span><%= tag_name %></span></a>

app/views/shared/_vote_buttons.html.erb
<% if signed_in? %>

  <%= link_to vote_for_proposal_path(proposal), :class => "btn btn-default btn-success", :title => "Concordo com esta proposta.", :method => :post do %>
    <b><i class="fa fa-thumbs-up"></i>&nbsp;<%= proposal.upvotes %></b>
  <% end %>
  &nbsp;
  <%= link_to vote_against_proposal_path(proposal), :class => "btn btn-default btn-danger", :title => "Discordo desta proposta", :method => :post do %>
    <b><i class="fa fa-thumbs-down"></i>&nbsp;<%= proposal.downvotes %></b>
  <% end %>

<% else %>

  <%= link_to signin_path, :class => "btn btn-default btn-success disabled", :title => "Precisa estar autenticado para votar." do %>
    <b><i class="fa fa-thumbs-up"></i>&nbsp;<%= proposal.upvotes %></b>
  <% end %>
  &nbsp;
  <%= link_to signin_path, :class =>"btn btn-default btn-danger disabled", :title => "Precisa estar autenticado para votar." do %>
    <b><i class="fa fa-thumbs-down"></i>&nbsp;<%= proposal.downvotes %></b>
  <% end %>

<% end %>