config/routes.rb
Dcid::Application.routes.draw do
  resources :users
  resources :password_resets
  resources :sessions,  only: [:new, :create, :destroy]
  resources :proposals do
    member do
      post :vote_for, :vote_against
    end
  end

  root 'static_pages#home'

  get   '/tags/:tag', to: 'proposals#tagged',   :as => 'tag'
  match '/tags',      to: 'proposals#tags',     via: 'get'
  match '/change_proposal_order', to: 'proposals#change_order', via: 'get'

  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/how',     to: 'static_pages#how',     via: 'get'
  match '/terms',   to: 'static_pages#terms',   via: 'get'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404', via: 'get'
  end

end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  is_impressionable

  belongs_to :user
  acts_as_voteable # thumbs_up gem
  acts_as_taggable # acts_as_taggable_on gem

  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 60 }
  validates :problem, presence: true, length: { maximum: 400 }
  validates :solution, presence: true, length: { maximum: 700 }

  before_save :normalize_tags

  default_scope -> { order('created_at DESC') }

  def score
    self.plusminus
  end

  def upvotes
    self.votes_for
  end

  def downvotes
    self.votes_against
  end

  def total_votes
    self.votes_for + self.votes_against
  end

  def normalize_tags
    # Make lowercase
    self.tag_list.map!(&:downcase)

    # Replace any non-word ([^\w]) characters with a hyphen
    self.tag_list.map! {|tag| tag.gsub(/[^\w]+/i,'-')}
  end

  def summary(maxChars)
    summary = self.solution
    if summary.length < maxChars then
      summary
    else
      indexOfLastCompleteWord = summary.rindex(" ", maxChars-3)   # provides space for the "..." (3 chars)
      summary[0, indexOfLastCompleteWord] + "..."
    end
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :signed_in_user,        only: [:new, :create, :show, :vote_for, :vote_against]
  before_action :admin_or_author_user,  only: [:edit, :update, :destroy]

  impressionist :unique => [:session_hash], :actions => [:show]

  def index
    if params[:order]
      @proposals = change_order(params[:order]).paginate(page: params[:page])
    else
      @proposals = Proposal.paginate(page: params[:page])
    end
  end

  def new
    @proposal = Proposal.new
  end

  def create
    @proposal = current_user.proposals.build(proposal_params)
    if @proposal.save
      flash[:success] = "Proposta submetida."
      redirect_to @proposal
    else
      render 'new'
    end
  end

  def edit
    @proposal = Proposal.find(params[:id])
  end

  def show
    @proposal = Proposal.find(params[:id])
  end

  def update
    @proposal = Proposal.find(params[:id])  # TODO FIXME this shouldn't be needed
    if @proposal.update_attributes(proposal_params)
      flash[:success] = "Proposta alterada."
      redirect_to @proposal
    else
      render 'edit'
    end
  end

  def destroy
    @proposal = Proposal.find(params[:id])  # TODO FIXME this shouldn't be needed
    @proposal.destroy
    flash[:success] = "Proposta apagada."
    redirect_to user_path(current_user)
  end

  def vote_for
    # TODO show updated number to user AJAX: http://goo.gl/byMMZ2
    begin
      current_user.vote_for(@proposal = Proposal.find(params[:id]))
      flash[:success] = "Voto efectuado."
    rescue ActiveRecord::RecordInvalid
      flash[:error] = "Voto não efectuado: só pode votar uma vez e não pode alterá-lo."
    end
    respond_to do |format|
      format.js
      format.html {redirect_to :back}
    end
  end

  def vote_against
    # TODO show updated number to user AJAX: http://goo.gl/byMMZ2
    begin
      current_user.vote_against(@proposal = Proposal.find(params[:id]))
      flash[:success] = "Voto efectuado."
    rescue ActiveRecord::RecordInvalid
      flash[:error] = "Voto não efectuado: só pode votar uma vez e não pode alterá-lo."
    end
    respond_to do |format|
      format.js
      format.html {redirect_to :back}
    end
  end

  def change_order(new_order)
    case new_order
      when 'recent'
        Proposal.order('created_at DESC')
      when 'voted'
        Proposal.all.sort { |p1, p2| p2.total_votes <=> p1.total_votes }
      when 'popular'
        Proposal.all.sort { |p1, p2| p2.impressionist_count(start_date: Date.today, end_date: Date.today.prev_month) <=> 
          p1.impressionist_count(start_date: Date.today, end_date: Date.today.prev_month) }
      when 'polemic'
        Proposal.all
          .select { |proposal| 
            proposal.total_votes > CONTROVERSIAL_THRESHOLD && 
            proposal.score <= 0.1*CONTROVERSIAL_THRESHOLD && 
            proposal.score > -0.1*CONTROVERSIAL_THRESHOLD }
          .sort{ |p1, p2| p2.total_votes <=> p1.total_votes }
      else
        Proposal.order('created_at DESC')
    end
  end


  # ==== Begin of tag-related views
  def tagged
    if params[:tag].present?
      @proposals = Proposal.tagged_with(params[:tag])
    else
      @proposals = []
    end
  end
  # ==== End of tag-related views

  private

    def proposal_params
      params.require(:proposal).permit(:title, :problem, :solution, :tag_list)
    end

    # Before filters

    def admin_or_author_user
      allowed = current_user.admin?
      if !allowed
        @proposal = current_user.proposals.find_by(id: params[:id])
        redirect_to(root_url) if @proposal.nil?
      end
    end

end

app/views/proposals/_proposal.html.erb
<div class="row-fluid">
  <div class="col-md-12" style="background-color: #EEEEEE">
    <div class="col-md-3 text-center">
      <h3><%= proposal.score %></h3>
      <p><%= render 'shared/vote_buttons', :proposal => proposal %></p>
    </div>
    <div class="col-md-9">
      <h4><%= link_to proposal.title, proposal %></h4>
      <%= render 'shared/span_tag_labels', :tags => proposal.tag_list %>
      <!--high-res -->
      <div class="hidden-xs">
        <br>
        <small class="text-muted">Proposto por <%= render 'shared/link_to_user', :user => proposal.user %> em <%= proposal.created_at.to_time.strftime('%e/%m/%Y') %></small>
      </div>
      <!--low-res empty space-->
      <div class="visible-xs-inline hidden-sm hidden-md hidden-lg">
        <small class="text-muted"><%= render 'shared/link_to_user', :user => proposal.user %> em <%= proposal.created_at.to_time.strftime('%e/%m/%Y') %></small>
      </div>
    </div>
  </div>
</div>

<!--empty line-->
<div class="row-fluid"><div class="col-md-12"><br></div></div>

app/views/proposals/_proposal_form.html.erb
<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <%= form_for(@proposal, html: {role: 'form'}) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="form-group">
      <%= f.label :title, "Título" %>
      <%= f.text_field :title, maxlength: 60, placeholder: "Uma frase a que seja possível responder 'Sim' ou 'Não'", class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :problem, "Problema" %>
      <%= f.text_area :problem, rows: 5, maxlength: 500, placeholder: "(max. 500 caract.)", class: 'form-control' %>
    </div>

    <div class="form-group">
      <div id="solution_field"></div>
      <%= f.label :solution, "Solução" %>
      <%= f.text_area :solution, rows: 8, maxlength: 1000, placeholder: "(max. 1000 caract.)", class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :tag_list, "Temas" %>
      <%= f.text_field :tag_list, maxlength: 255, placeholder: "separados, por, vírgulas", class: 'form-control' %>
    </div>

    <br>
      <% if edit %>
      <div class="form-group">
        <%= f.submit "Guardar alterações", class: "pull-right btn btn-success" %>
        <%= link_to 'Cancelar', @proposal, class: "pull-right btn btn-default" %>
      </div>
      <% else %>
      <%= f.submit "Submeter", class: "btn btn-default btn-success" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/proposals/edit.html.erb
<% provide(:title, 'Editar proposta') %>

<div class="row">
  <div class="span12">

    <h1>Edite a sua proposta</h1>

    <%= render 'proposal_form', edit: true %>
  </div>
</div>

app/views/proposals/index.html.erb
<% provide(:title, 'Propostas') %>

<div class="row">
  <div class="col-md-12">

    <h1>Todas as propostas</h1>

    <div class="dropdown pull-right">
      <button class="btn dropdown-toggle" type="button" data-toggle="dropdown">
        Ordenar por
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu">
        <li role="presentation"><a id="recent" role="menuitem" tabindex="0" href="/proposals?order=recent">Mais recentes</a></li>
        <li role="presentation"><a id="voted" role="menuitem" tabindex="1" href="/proposals?order=voted">Mais votadas</a></li>
        <li role="presentation"><a id="popular" role="menuitem" tabindex="2" href="/proposals?order=popular">Mais populares</a></li>
        <li role="presentation"><a id="polemic" role="menuitem" tabindex="3" href="/proposals?order=polemic">Mais polémicas</a></li>
      </ul>
    </div>
    <div class="new-proposal pull-right">
      <%= link_to '<button class="btn btn-success">Criar proposta</button>'.html_safe, new_proposal_path %>
    </div>

    <br><br><br>

    <% if @proposals.empty? %>
        <p class="text-center">Não foram encontradas propostas.</p>
      <% else %>
        <ul>
          <%= render @proposals %>
        </ul>
    <% end %>

  </div>
</div>

<div class="row">
  <div class="col-md-12 text-center">
    <%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
  </div>
</div>

app/views/proposals/new.html.erb
<% provide(:title, 'Criar proposta') %>

<div class="row">
  <div class="col-md-12">
    <h1>A sua proposta</h1>

    <%= render 'proposal_form', edit: false %>
      </div>
    </div>
  </div>
</div>

app/views/proposals/show.html.erb
<% provide(:title, @proposal.title) %>

<div class="row">
  <div class="col-md-12">
    <h2><%= @proposal.title %></h2>
    <br>
    <div class="row">
      <div class="col-md-9">
        <p><%= @proposal.problem %></p>
        <br>
        <h3>Solução</h3>
        <p><%= @proposal.solution %></p>
        <br class="visible-xs"> <!-- separates text -->
      </div>
      <div class="col-md-3 text-center">
        <p><%= render 'shared/vote_buttons', :proposal => @proposal %></p>
        <p><%= render 'shared/list_tag_labels', :tags => @proposal.tag_list %></p>
        <p><%= render 'shared/link_to_user', :user => @proposal.user %> em <%= @proposal.created_at.to_time.strftime('%e/%m/%Y') %></p>
        <% if current_user.admin? || current_user?(@proposal.user) %>
          <%= link_to '<i class="fa fa-pencil"></i>&nbsp;Editar'.html_safe, edit_proposal_path, class: "btn btn-default btn-sm" %>
        <% end %>
        <% if current_user.admin? || current_user?(@proposal.user) %>
          <%= link_to '<i class="fa fa-trash-o"></i>&nbsp;Apagar'.html_safe, @proposal, class: "btn btn-default btn-sm",
                method: :delete, data: { confirm: "De certeza?" }, title: @proposal.title %>
        <% end %>
      </div>
    </div>
    <br>
    <div class="row">
      <div class="span12">
        <h3>Comentários</h3>
        <div class="fb-comments" data-href="<%= request.original_url %>" data-numposts="10" data-colorscheme="light"></div>
      </div>
    </div>
  </div>
</div>

app/views/proposals/tagged.html.erb
<% provide(:title, "Propostas do tema: #{params[:tag]}") %>

<div class="row">
  <div class="span12">

    <h1>Propostas do tema "<%= params[:tag] %>"</h1>

    <p><%= link_to '<button class="btn btn-success pull-right">Criar proposta</button>'.html_safe, new_proposal_path %></p>
    <br><br><br>

    <% if @proposals.empty? %>
        <p class="text-center">Não foram encontradas propostas.</p>
      <% else %>
        <ul>
          <%= render @proposals %>
        </ul>
    <% end %>

  </div>
</div>

app/views/proposals/tags.html.erb
<% provide(:title, 'Temas') %>

<div class="row">
  <div class="span12">

    <h1>Todos os temas</h1>

    <p>Um tema é uma ou mais palavras-chave que categorizam uma proposta. Estes temas agrupam propostas relacionadas e tornam mais fácil outros cidadãos encontrarem a sua proposta.</p>
    <br>

    <div>
      <div> <!-- as seen on goo.gl/mJiwTA needs refactor -->
        <% tag_cloud Proposal.tag_counts.sort_by!{ |tag| tag.name }, %w[s m l] do |tag| %>
          <a class="label label-default" href="<%= tag_path(tag.name) %>"><span><%= tag.name %></span></a>
        <% end %>
      </div>

    </div>

  </div>
</div>