config/routes.rb
Dcid::Application.routes.draw do
  resources :users
  resources :password_resets
  resources :sessions,  only: [:new, :create, :destroy]
  resources :proposals do
    member do
      post :vote_for, :vote_against
    end
  end

  root 'static_pages#home'

  get   '/tags/:tag', to: 'proposals#tagged',   :as => 'tag'
  match '/tags',      to: 'proposals#tags',     via: 'get'
  match '/change_proposal_order', to: 'proposals#change_order', via: 'get'

  match '/home',    to: 'static_pages#home',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/how',     to: 'static_pages#how',     via: 'get'
  match '/terms',   to: 'static_pages#terms',   via: 'get'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', to: 'errors#error_404', via: 'get'
  end

end

app/views/layouts/_analytics.html.erb
<!--GoogleAnalytics-->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-10714206-8', 'dcid.org');
  ga('send', 'pageview');
</script>

app/views/layouts/_fbcomments.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= link_to 'DCID '+app_version(), about_path %>&nbsp;é ainda um protótipo!&nbsp;<%= mail_to "dialex.nunes@outlook.com", "Queres ajudar?", subject: "DCID Equipa", body: "Gostava de ajudar-vos da seguinte maneira " %>
  </small>
  <nav>
    <ul>
      <!--<li><%= link_to "Quem somos",   about_path %></li>-->
      <li><%= link_to "Termos de utilização", terms_path %></li>
      <li><%= mail_to "dialex.nunes@outlook.com", "Contacto", subject: "DCID Suporte" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to image_tag("logo-dcid.png", alt: "DCID", width: "75"), root_path, id: "logo" %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <!-- left buttons, EMPTY for now -->
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <% if signed_in? %>
            <li><%= link_to '<i class="fa fa-comment"></i> Propostas'.html_safe, proposals_path %></li>
            <li><%= link_to '<i class="fa fa-tags"></i> Temas'.html_safe, tags_path %></li>
            <li><%= link_to '<i class="fa fa-group"></i> Cidadãos'.html_safe, users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user fa-fw"></i> <%= current_user.welcome_name %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "Perfil",  current_user %></li>
                <li><%= link_to '<i class="fa fa-cog"></i> Definições'.html_safe, edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li><%= link_to '<i class="fa fa-sign-out"></i> Sair'.html_safe, signout_path, method: "delete" %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Como funciona?", how_path %></li>
            <li><%= link_to '<i class="fa fa-comment"></i> Propostas'.html_safe, proposals_path %></li>
            <li><%= link_to '<i class="fa fa-sign-in fa-fw"></i> Entrar'.html_safe, signin_path %></li>
          <% end %>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <link href='http://fonts.googleapis.com/css?family=Lato:400,700,400italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,700' rel='stylesheet' type='text/css'>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= yield :head %>
  </head>
  <body>
    <%= render 'layouts/fbcomments' %>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %> text-center"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= render 'layouts/analytics' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>